//! `toon-provider dash` (TOON_Network#174, ADR 0029): a full-screen view over
//! the document `status --json` prints.
//!
//! Every frame here is drawn from a `status --json --check` fixture under
//! `tests/fixtures/status/` (generated by `tests/status_cli.rs` from the real
//! `gather` and `to_json`), read back with `status::from_json`, into
//! ratatui's `TestBackend`. The text of each frame is an `insta` snapshot
//! under `tests/snapshots/`; the colours are asserted cell by cell, since a
//! text snapshot cannot see them. The key handling — the only thing between
//! a keypress and money moving — is driven key by key.

use std::path::PathBuf;

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use ratatui::backend::TestBackend;
use ratatui::buffer::Buffer;
use ratatui::style::Color;
use ratatui::Terminal;

use toon_provider::dash::{draw, App, Effect, Modal, Update};
use toon_provider::redeem::gas::{Chain, Estimate};
use toon_provider::status::{
    from_json, parse_duration, parse_sol, Report, Section, Thresholds, DEFAULT_MIN_RUNWAY,
    DEFAULT_MIN_SOL,
};

const KEY: &str = "4242424242424242424242424242424242424242424242424242424242424242";
const KEYID: &str = "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12";

fn fixture(name: &str) -> Report {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/status")
        .join(format!("{name}.json"));
    let doc = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
    from_json(&doc).unwrap()
}

/// `status`'s default thresholds: `--min-runway 7d`, `--min-sol 0.005`.
fn thresholds() -> Thresholds {
    Thresholds {
        min_runway_s: parse_duration(DEFAULT_MIN_RUNWAY).unwrap(),
        min_lamports: parse_sol(DEFAULT_MIN_SOL).unwrap(),
    }
}

fn app_with(name: &str) -> App {
    let mut app = App::new(thresholds());
    app.apply(Update::Report(Box::new(fixture(name))));
    app
}

fn buffer(app: &App, width: u16, height: u16) -> Buffer {
    let mut terminal = Terminal::new(TestBackend::new(width, height)).unwrap();
    terminal
        .draw(|frame| {
            draw(frame, app);
        })
        .unwrap();
    terminal.backend().buffer().clone()
}

fn text(buffer: &Buffer) -> String {
    let area = buffer.area;
    let mut out = String::new();
    for y in 0..area.height {
        let mut line = String::new();
        for x in 0..area.width {
            line.push_str(buffer[(x, y)].symbol());
        }
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out
}

fn frame(app: &App) -> String {
    text(&buffer(app, 120, 40))
}

/// Where `needle` starts on screen.
fn find(buffer: &Buffer, needle: &str) -> (u16, u16) {
    let area = buffer.area;
    for y in 0..area.height {
        let row: Vec<&str> = (0..area.width).map(|x| buffer[(x, y)].symbol()).collect();
        let line = row.concat();
        if let Some(byte) = line.find(needle) {
            // Columns, not bytes: every cell before it holds one symbol.
            let x = line[..byte].chars().count() as u16;
            return (x, y);
        }
    }
    panic!("{needle:?} is not on screen:\n{}", text(buffer));
}

fn key(code: KeyCode) -> KeyEvent {
    KeyEvent::new(code, KeyModifiers::NONE)
}

fn press(app: &mut App, code: KeyCode) -> Option<Effect> {
    app.handle_key(key(code))
}

fn type_text(app: &mut App, text: &str) {
    for c in text.chars() {
        assert!(press(app, KeyCode::Char(c)).is_none(), "typing {c:?}");
    }
}

// ── The six panes ─────────────────────────────────────────────────────────────

#[test]
fn a_healthy_box() {
    let app = app_with("healthy");
    let screen = frame(&app);
    insta::assert_snapshot!("healthy", screen);
}

#[test]
fn a_box_with_something_wrong_in_every_section() {
    insta::assert_snapshot!("troubled", frame(&app_with("troubled")));
}

#[test]
fn a_provider_that_does_not_answer() {
    insta::assert_snapshot!("provider_down", frame(&app_with("provider_down")));
}

#[test]
fn a_narrow_terminal_stacks_the_panes() {
    insta::assert_snapshot!(
        "troubled_narrow",
        text(&buffer(&app_with("troubled"), 80, 60))
    );
}

#[test]
fn before_the_first_report_it_says_so() {
    let app = App::new(thresholds());
    assert!(
        frame(&app).contains("reading the status"),
        "{}",
        frame(&app)
    );
}

#[test]
fn the_six_panes_are_in_adr_0029s_order() {
    for name in ["healthy", "troubled", "provider_down"] {
        let screen = buffer(&app_with(name), 120, 40);
        let at: Vec<(u16, u16)> = Section::ALL
            .iter()
            .map(|s| find(&screen, &format!(" {} ", s.title())))
            .collect();
        // Read left to right, top to bottom: two columns, three rows.
        let reading = |p: &(u16, u16)| (p.1, p.0);
        assert!(
            at.windows(2).all(|w| reading(&w[0]) < reading(&w[1])),
            "{name}: {at:?}"
        );
    }
}

// ── What `--check` would fail on is highlighted ───────────────────────────────

#[test]
fn a_pane_check_fails_on_is_red_and_the_rest_are_not() {
    let screen = buffer(&app_with("troubled"), 120, 40);
    for section in [
        Section::Identity,
        Section::Directory,
        Section::Publisher,
        Section::Funding,
    ] {
        let (x, y) = find(&screen, &format!(" {} ", section.title()));
        assert_eq!(
            screen[(x + 1, y)].fg,
            Color::Red,
            "{} is not highlighted",
            section.title()
        );
    }
    // Earnings could not be read: a warning, not a problem.
    let (x, y) = find(&screen, " EARNINGS ");
    assert_eq!(screen[(x + 1, y)].fg, Color::Yellow);
    let (x, y) = find(&screen, " LEASES ");
    assert_ne!(screen[(x + 1, y)].fg, Color::Red);

    let healthy = buffer(&app_with("healthy"), 120, 40);
    for section in Section::ALL {
        let (x, y) = find(&healthy, &format!(" {} ", section.title()));
        assert!(
            ![Color::Red, Color::Yellow].contains(&healthy[(x + 1, y)].fg),
            "{} is highlighted on a healthy box",
            section.title()
        );
    }
}

#[test]
fn each_problem_is_listed_in_red_above_the_panes() {
    let app = app_with("troubled");
    let screen = buffer(&app, 120, 40);
    let problems = app.outcome().problems.clone();
    assert_eq!(problems.len(), 4, "{problems:?}");
    let (x, y) = find(&screen, "identity: the Profile's connector_seal_key");
    assert_eq!(screen[(x, y)].fg, Color::Red);
    let (dx, dy) = find(&screen, " IDENTITY ");
    assert!(y < dy || (y == dy && x < dx));
}

#[test]
fn a_refused_relay_line_is_red() {
    let screen = buffer(&app_with("troubled"), 120, 40);
    let (x, y) = find(&screen, "REFUSED");
    assert_eq!(screen[(x, y)].fg, Color::Red);
}

#[test]
fn the_threshold_is_the_operators() {
    // The healthy box holds 1.5 SOL: fine at 0.005, a problem at 2.
    let mut app = App::new(Thresholds {
        min_runway_s: 7 * 86_400,
        min_lamports: 2_000_000_000,
    });
    app.apply(Update::Report(Box::new(fixture("healthy"))));
    let screen = buffer(&app, 120, 40);
    let (x, y) = find(&screen, " FUNDING ");
    assert_eq!(screen[(x + 1, y)].fg, Color::Red);
}

// ── Refresh ───────────────────────────────────────────────────────────────────

#[test]
fn it_refreshes_on_the_liveness_cadence() {
    let app = app_with("healthy");
    assert_eq!(app.cadence_s(), 60, "the fixture's liveness_cadence_s");
    // No provider, no cadence of its own: a minute.
    assert_eq!(app_with("provider_down").cadence_s(), 60);
    assert_eq!(App::new(thresholds()).cadence_s(), 60);
}

#[test]
fn u_refreshes_now_and_q_quits() {
    let mut app = app_with("healthy");
    assert!(matches!(
        press(&mut app, KeyCode::Char('u')),
        Some(Effect::Refresh)
    ));
    assert!(matches!(
        press(&mut app, KeyCode::Char('q')),
        Some(Effect::Quit)
    ));
    let ctrl_c = KeyEvent::new(KeyCode::Char('c'), KeyModifiers::CONTROL);
    assert!(matches!(app.handle_key(ctrl_c), Some(Effect::Quit)));
}

#[test]
fn a_refresh_keeps_an_open_dialog() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('t'));
    type_text(&mut app, "12");
    app.apply(Update::Report(Box::new(fixture("healthy"))));
    assert!(matches!(app.modal(), Some(Modal::TopupAmount { .. })));
    assert!(frame(&app).contains("12"));
}

// ── Redeem ────────────────────────────────────────────────────────────────────

#[test]
fn redeem_offers_the_same_channels_as_toon_provider_redeem() {
    let mut app = app_with("healthy");
    let Some(Effect::EstimateGas {
        round,
        channels: candidates,
    }) = press(&mut app, KeyCode::Char('r'))
    else {
        panic!("r asks for gas estimates for the channels it offers");
    };
    let ids: Vec<&str> = candidates.iter().map(|c| c.channel_id.as_str()).collect();
    assert_eq!(
        ids,
        [
            "0xabababababababababababababababababababababababababababababababab",
            "2aEVJ8koKD8LTZrLRSGtAtU7LBt4e7QjjCgf1kzQ7Rip",
        ]
    );
    assert!(frame(&app).contains("estimating"), "{}", frame(&app));
    app.apply(Update::Estimates {
        round,
        estimates: estimates(),
    });
    insta::assert_snapshot!("redeem_pick", frame(&app));
}

#[test]
fn redeem_needs_a_pick_a_typed_confirmation_and_the_key() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('r'));

    // Enter with nothing picked goes nowhere.
    assert!(press(&mut app, KeyCode::Enter).is_none());
    assert!(matches!(app.modal(), Some(Modal::RedeemPick { .. })));

    // Pick the second row only.
    press(&mut app, KeyCode::Down);
    press(&mut app, KeyCode::Char(' '));
    assert!(press(&mut app, KeyCode::Enter).is_none());
    assert!(matches!(app.modal(), Some(Modal::Confirm { .. })));
    assert!(frame(&app).contains("600"), "{}", frame(&app));

    // One keypress never spends: Enter before `y` does nothing, and a key
    // other than Enter after `y` disarms it.
    assert!(press(&mut app, KeyCode::Enter).is_none());
    press(&mut app, KeyCode::Char('y'));
    press(&mut app, KeyCode::Char('x'));
    assert!(press(&mut app, KeyCode::Enter).is_none());
    assert!(matches!(app.modal(), Some(Modal::Confirm { .. })));
    press(&mut app, KeyCode::Char('y'));
    assert!(press(&mut app, KeyCode::Enter).is_none());
    assert!(matches!(app.modal(), Some(Modal::RedeemKey { .. })));

    type_text(&mut app, KEY);
    let screen = frame(&app);
    assert!(
        !screen.contains(&KEY[..8]),
        "the key is on screen:\n{screen}"
    );
    insta::assert_snapshot!("redeem_key", screen);

    let Some(Effect::Redeem { channels, key }) = press(&mut app, KeyCode::Enter) else {
        panic!("Enter with a key redeems");
    };
    assert_eq!(
        channels
            .iter()
            .map(|c| c.channel_id.as_str())
            .collect::<Vec<_>>(),
        ["2aEVJ8koKD8LTZrLRSGtAtU7LBt4e7QjjCgf1kzQ7Rip"]
    );
    assert_eq!(toon_provider::redeem::sign::keyid_hex(&key), KEYID);
    assert!(matches!(app.modal(), Some(Modal::Working { .. })));

    // Keys do nothing while the redeem runs; its outcome is shown, and the
    // report is read again.
    assert!(press(&mut app, KeyCode::Esc).is_none());
    app.apply(Update::Redeemed("  redeemed  2aEV…: 600 collected".into()));
    assert!(matches!(
        app.apply(Update::RedeemFinished),
        Some(Effect::Refresh)
    ));
    assert!(frame(&app).contains("600 collected"));
    press(&mut app, KeyCode::Enter);
    assert!(app.modal().is_none());
}

#[test]
fn a_malformed_key_is_refused_without_being_repeated_and_the_field_cleared() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('r'));
    press(&mut app, KeyCode::Char('a'));
    press(&mut app, KeyCode::Enter);
    press(&mut app, KeyCode::Char('y'));
    press(&mut app, KeyCode::Enter);
    type_text(&mut app, &KEY[..40]);
    assert!(press(&mut app, KeyCode::Enter).is_none());
    let screen = frame(&app);
    assert!(screen.contains("64 hex characters"), "{screen}");
    assert!(!screen.contains(&KEY[..8]), "{screen}");
    let Some(Modal::RedeemKey { typed, .. }) = app.modal() else {
        panic!("still asking for the key");
    };
    assert_eq!(*typed, 0, "the field is cleared");
}

#[test]
fn escape_backs_out_of_redeem_at_every_step() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('r'));
    press(&mut app, KeyCode::Esc);
    assert!(app.modal().is_none());

    press(&mut app, KeyCode::Char('r'));
    press(&mut app, KeyCode::Char('a'));
    press(&mut app, KeyCode::Enter);
    press(&mut app, KeyCode::Char('y'));
    press(&mut app, KeyCode::Enter);
    type_text(&mut app, &KEY[..10]);
    assert!(press(&mut app, KeyCode::Esc).is_none());
    assert!(app.modal().is_none());
}

#[test]
fn nothing_to_redeem_says_why() {
    let mut app = app_with("troubled");
    assert!(press(&mut app, KeyCode::Char('r')).is_none());
    assert!(app.modal().is_none());
    assert!(frame(&app).contains("nothing to redeem"), "{}", frame(&app));
}

fn estimates() -> std::collections::BTreeMap<Chain, Estimate> {
    [
        (Chain::Evm, Estimate::Unknown("no EVM RPC".into())),
        (Chain::Solana, Estimate::Solana { lamports: 10_000 }),
    ]
    .into()
}

#[test]
fn estimates_that_land_after_enter_still_reach_the_confirmation() {
    let mut app = app_with("healthy");
    let Some(Effect::EstimateGas { round, .. }) = press(&mut app, KeyCode::Char('r')) else {
        panic!("r asks for estimates");
    };
    press(&mut app, KeyCode::Down);
    press(&mut app, KeyCode::Char(' '));
    press(&mut app, KeyCode::Enter);
    press(&mut app, KeyCode::Char('y'));
    assert!(frame(&app).contains("gas unknown"), "{}", frame(&app));
    app.apply(Update::Estimates {
        round,
        estimates: estimates(),
    });
    let screen = frame(&app);
    assert!(screen.contains("gas ~0.00001 SOL"), "{screen}");
    let Some(Modal::Confirm { armed, .. }) = app.modal() else {
        panic!("still confirming");
    };
    assert!(*armed, "an estimate landing does not disarm the dialog");
}

#[test]
fn estimates_for_a_dialog_since_closed_are_not_taken_for_the_open_one() {
    let mut app = app_with("healthy");
    let Some(Effect::EstimateGas { round: stale, .. }) = press(&mut app, KeyCode::Char('r')) else {
        panic!("r asks for estimates");
    };
    press(&mut app, KeyCode::Esc);
    press(&mut app, KeyCode::Char('r'));
    app.apply(Update::Estimates {
        round: stale,
        estimates: estimates(),
    });
    assert!(frame(&app).contains("estimating"), "{}", frame(&app));
}

#[test]
fn ctrl_c_waits_while_money_is_moving() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('t'));
    type_text(&mut app, "1");
    press(&mut app, KeyCode::Enter);
    press(&mut app, KeyCode::Char('y'));
    press(&mut app, KeyCode::Enter);
    let ctrl_c = KeyEvent::new(KeyCode::Char('c'), KeyModifiers::CONTROL);
    assert!(app.handle_key(ctrl_c).is_none());
    assert!(frame(&app).contains("Ctrl-C waits"), "{}", frame(&app));
    app.apply(Update::ToppedUp(Ok("{}".into())));
    assert!(matches!(app.handle_key(ctrl_c), Some(Effect::Quit)));
}

#[test]
fn a_pane_scrolls_no_further_than_its_last_line() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('2'));
    let limits = {
        let mut terminal = Terminal::new(TestBackend::new(120, 40)).unwrap();
        let mut limits = None;
        terminal
            .draw(|frame| limits = Some(draw(frame, &app)))
            .unwrap();
        limits.unwrap()
    };
    let limit = limits[&Section::Directory];
    assert!(
        limit > 0,
        "the fixture's directory does not fit: {limits:?}"
    );
    app.set_scroll_limits(limits);
    for _ in 0..50 {
        press(&mut app, KeyCode::Char('j'));
    }
    assert_eq!(app.scroll(Section::Directory), limit);
    press(&mut app, KeyCode::Char('k'));
    assert_eq!(app.scroll(Section::Directory), limit - 1);
}

// ── Top up ────────────────────────────────────────────────────────────────────

#[test]
fn top_up_asks_an_amount_and_a_typed_confirmation() {
    let mut app = app_with("healthy");
    assert!(press(&mut app, KeyCode::Char('t')).is_none());
    // Only digits are taken.
    type_text(&mut app, "5x00.0000");
    let Some(Modal::TopupAmount { input, .. }) = app.modal() else {
        panic!("t asks for an amount");
    };
    assert_eq!(input, "5000000");
    assert!(press(&mut app, KeyCode::Enter).is_none());
    insta::assert_snapshot!("topup_confirm", frame(&app));

    assert!(press(&mut app, KeyCode::Enter).is_none(), "not armed yet");
    press(&mut app, KeyCode::Char('y'));
    let Some(Effect::Topup { amount }) = press(&mut app, KeyCode::Enter) else {
        panic!("y then Enter tops up");
    };
    assert_eq!(amount, "5000000");
    assert!(matches!(app.modal(), Some(Modal::Working { .. })));

    assert!(matches!(
        app.apply(Update::ToppedUp(Ok("{\"deposit\": \"15000000\"}".into()))),
        Some(Effect::Refresh)
    ));
    assert!(frame(&app).contains("15000000"));
}

#[test]
fn a_zero_amount_is_refused_before_anything_is_asked() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('t'));
    type_text(&mut app, "000");
    assert!(press(&mut app, KeyCode::Enter).is_none());
    assert!(matches!(app.modal(), Some(Modal::TopupAmount { .. })));
    assert!(frame(&app).contains("greater than zero"), "{}", frame(&app));
}

#[test]
fn a_refused_top_up_is_shown() {
    let mut app = app_with("healthy");
    press(&mut app, KeyCode::Char('t'));
    type_text(&mut app, "1");
    press(&mut app, KeyCode::Enter);
    press(&mut app, KeyCode::Char('y'));
    press(&mut app, KeyCode::Enter);
    app.apply(Update::ToppedUp(Err(
        "top-up refused: 400 Bad Request".into()
    )));
    assert!(frame(&app).contains("400 Bad Request"));
}

#[test]
fn no_publisher_no_top_up() {
    let mut report = fixture("healthy");
    report.publisher.url = None;
    report.publisher.status = None;
    report.publisher.error = Some("no publish_url is configured, so there is no publisher".into());
    let mut app = App::new(thresholds());
    app.apply(Update::Report(Box::new(report)));
    assert!(press(&mut app, KeyCode::Char('t')).is_none());
    assert!(app.modal().is_none());
    assert!(frame(&app).contains("no publisher"), "{}", frame(&app));
}

// ── ADR 0028's visual rule ────────────────────────────────────────────────────

/// "The TUI draws with no colour of its own: every style is an ANSI colour
/// or a modifier." `Color::Rgb` and `Color::Indexed` are how ratatui names a
/// colour the terminal's theme cannot override.
#[test]
fn the_dash_names_no_colour_outside_the_ansi_palette() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/dash");
    let mut offenders = Vec::new();
    for entry in std::fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        let source = std::fs::read_to_string(&path).unwrap();
        for (n, line) in source.lines().enumerate() {
            if line.contains("Color::Rgb") || line.contains("Color::Indexed") {
                offenders.push(format!("{}:{}: {}", path.display(), n + 1, line.trim()));
            }
        }
    }
    assert!(offenders.is_empty(), "{}", offenders.join("\n"));

    for name in ["healthy", "troubled", "provider_down"] {
        let screen = buffer(&app_with(name), 120, 40);
        for cell in screen.content() {
            for colour in [cell.fg, cell.bg] {
                assert!(
                    !matches!(colour, Color::Rgb(..) | Color::Indexed(_)),
                    "{name}: {colour:?}"
                );
            }
        }
    }
}
