// The grant tool (`grant.mjs`), which needs no network, no chain and no
// mnemonic: what it signs, what it refuses before signing, and that what it
// signs is the same bytes the provider was proven against. Run with
// `npm test` in this directory.
//
// The proof is against the REAL thing, not against this tool: the M5-1 wire
// fixtures under ../../tests/fixtures/wire/ were generated by the provider's
// own event builder and HTTP surface over fixed keys, a fixed clock and zero
// signing randomness (`tests/wire_fixtures.rs`). Re-deriving the fixture
// event here — same id, same signature — is what makes "a provider accepts
// what this tool produced" a fact about `status.granted.json` and not an
// assumption.

import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import { generateSecretKey, getPublicKey, verifyEvent } from 'nostr-tools/pure';

import {
  K_GATEWAY_GRANT,
  TOON_LABEL,
  checkGrant,
  grantAddress,
  grantEvent,
  optionsFrom,
  parseExpiry,
  parsePorts,
  publishGrant,
  signGrant,
} from './grant.mjs';

// ── the fixed world the fixtures were generated in ─────────────────────────

const FIXTURES = new URL('../../tests/fixtures/wire/', import.meta.url);
const fixture = (name) => JSON.parse(readFileSync(new URL(name, FIXTURES), 'utf8'));

const constants = fixture('constants.json');
const GRANT = fixture('gateway_grant.json');
const NOW = constants.now;
const TENANT_KEY = Uint8Array.from(Buffer.from(constants.tenant.secret_key, 'hex'));
const ZERO_AUX = new Uint8Array(32);

/** The fixture grant's inputs, exactly as a tenant would hand them to the tool. */
const FIXTURE_INPUTS = {
  workloadId: GRANT.content.workload_id,
  gateway: constants.gateway.public_key,
  httpPort: GRANT.content.http_port,
  ports: [GRANT.content.http_port],
  standbySet: GRANT.content.standby_set,
  expiresAt: GRANT.content.expires_at,
};

/** A fresh, valid set of inputs for the cases that vary one thing. */
const inputs = (overrides = {}) => ({ ...FIXTURE_INPUTS, ...overrides });

/** A relay writer that accepts every relay it is asked for, and remembers each write. */
const acceptingRelays = () => {
  const writes = [];
  return {
    writes,
    writeTo: async (relay, event) => {
      writes.push({ relay, event });
      return null;
    },
  };
};

/** A signer that must never be reached: the refusal comes first. */
const neverSigns = () => {
  throw new Error('signed a grant that should have been refused before signing');
};

describe('the kind and the label', () => {
  it('are the ones constants.json allocates, not numbers of their own', () => {
    assert.equal(K_GATEWAY_GRANT, constants.kinds.K_GATEWAY_GRANT);
    assert.equal(TOON_LABEL, constants.label);
  });
});

describe('the event a grant signs', () => {
  it('is the gateway_grant wire fixture, byte for byte — id and signature included', () => {
    // Zero aux randomness is the fixture generator's rule, never the tool's:
    // a real signer draws fresh randomness (`signGrant` without `auxRand`).
    const unsigned = grantEvent(FIXTURE_INPUTS, NOW);
    const event = signGrant(unsigned, TENANT_KEY, { auxRand: ZERO_AUX });

    assert.deepEqual(event, GRANT.event);
    assert.equal(
      JSON.stringify([0, event.pubkey, event.created_at, event.kind, event.tags, event.content]),
      GRANT.nip01_serialization,
    );
  });

  it('matches the fixture field for field: kind, d, p, L and the content shape', () => {
    const event = grantEvent(FIXTURE_INPUTS, NOW);

    assert.equal(event.kind, GRANT.event.kind);
    assert.deepEqual(event.tags, [
      ['d', FIXTURE_INPUTS.workloadId],
      ['p', FIXTURE_INPUTS.gateway],
      ['L', 'toon.network'],
    ]);
    assert.deepEqual(JSON.parse(event.content), GRANT.content);
    // The content is serialised in §3.1.3's declaration order, not sorted:
    // the fixture checker copies the signed string rather than rebuilding it,
    // and a sorted serialisation would hash to a different id.
    assert.deepEqual(Object.keys(JSON.parse(event.content)), [
      'workload_id',
      'gateway',
      'http_port',
      'standby_set',
      'expires_at',
    ]);
    assert.equal(event.content, GRANT.event.content);
  });

  it('carries the short name last when one is given, and not at all otherwise', () => {
    const named = grantEvent(inputs({ name: 'blog' }), NOW);
    assert.deepEqual(Object.keys(JSON.parse(named.content)), [
      'workload_id',
      'gateway',
      'http_port',
      'standby_set',
      'expires_at',
      'name',
    ]);
    assert.equal(JSON.parse(named.content).name, 'blog');

    const unnamed = grantEvent(FIXTURE_INPUTS, NOW);
    assert.equal('name' in JSON.parse(unnamed.content), false);
  });

  it('is signed by the tenant and verifies as a Nostr event', () => {
    const secretKey = generateSecretKey();
    const event = signGrant(grantEvent(FIXTURE_INPUTS, NOW), secretKey);

    assert.equal(event.pubkey, getPublicKey(secretKey));
    assert.ok(verifyEvent(event), 'the tenant signed it');
  });
});

describe('what a provider would refuse is refused here first, before anything is signed', () => {
  const refusal = async (overrides, pattern) => {
    const relays = acceptingRelays();
    await assert.rejects(
      publishGrant({
        grant: inputs(overrides),
        secretKey: TENANT_KEY,
        relays: ['ws://relay:7100'],
        writeTo: relays.writeTo,
        sign: neverSigns,
        now: () => NOW,
      }),
      pattern,
    );
    assert.deepEqual(relays.writes, [], 'nothing was published');
  };

  it('an expiry already past, naming the expiry and the clock', async () => {
    await refusal({ expiresAt: NOW - 1 }, /expires_at 1699999999 is already past \(now 1700000000\)/);
    await refusal({ expiresAt: NOW }, /expires_at 1700000000 is now: .*expired by the time a Workload Gateway carried it/);
    await refusal({ expiresAt: 'tomorrow' }, /expires_at must be unix seconds/);
  });

  it('a gateway key that is not a public key, naming the key', async () => {
    await refusal({ gateway: 'npub1notahexkey' }, /gateway .*"npub1notahexkey".*64 hex/);
    await refusal({ gateway: 'ABCD'.repeat(16) }, /gateway .*lowercase/);
    await refusal({ gateway: undefined }, /gateway .*required/);
  });

  it('a Standby Set member that is not a public key, or no Standby Set at all', async () => {
    await refusal({ standbySet: [] }, /Standby Set must name at least one provider, the primary first/);
    await refusal(
      { standbySet: [constants.provider.public_key, 'not-a-key'] },
      /Standby Set member 2 .*"not-a-key".*64 hex/,
    );
  });

  it('an http_port that is not one of the ports the tenant asked for, naming both', async () => {
    await refusal({ httpPort: 8080, ports: [443, 22] }, /http_port 8080 is not one of the spawn's container ports \(443, 22\)/);
    await refusal({ httpPort: 0, ports: [443] }, /http_port .*1 and 65535/);
    await refusal({ httpPort: 443, ports: [] }, /spawn's container ports .*at least one/);
  });

  it('a name that is not a single DNS label, saying which rule it breaks', async () => {
    await refusal({ name: 'my.blog' }, /name "my.blog".*single DNS label.*no dots/);
    await refusal({ name: 'Blog' }, /name "Blog".*lowercase/);
    await refusal({ name: '-blog' }, /name "-blog".*hyphen/);
    await refusal({ name: 'blog-' }, /name "blog-".*hyphen/);
    await refusal({ name: 'my_blog' }, /name "my_blog".*letters, digits and hyphens/);
    await refusal({ name: '' }, /name "".*empty/);
    await refusal({ name: 'a'.repeat(64) }, /name .*63/);
  });

  it('a workload id that is not 64 lowercase hex characters', async () => {
    await refusal({ workloadId: 'AA'.repeat(32) }, /workload id .*lowercase hex/);
    await refusal({ workloadId: 'aa' }, /workload id .*64/);
  });

  it('and `checkGrant` is the same rule on its own, for a caller that only wants the verdict', () => {
    assert.equal(checkGrant(FIXTURE_INPUTS, NOW), null);
    assert.match(checkGrant(inputs({ expiresAt: NOW - 1 }), NOW), /already past/);
    assert.match(checkGrant(inputs({ name: 'A' }), NOW), /lowercase/);
  });
});

describe('publishing', () => {
  it('signs once, writes to every relay named, and reports the id and where it landed', async () => {
    const relays = acceptingRelays();
    const secretKey = generateSecretKey();

    const report = await publishGrant({
      grant: inputs({ name: 'blog' }),
      secretKey,
      relays: ['ws://relay-a:7100', 'ws://relay-b:7100'],
      writeTo: relays.writeTo,
      now: () => NOW,
    });

    assert.equal(relays.writes.length, 2);
    assert.deepEqual(relays.writes.map((w) => w.relay), ['ws://relay-a:7100', 'ws://relay-b:7100']);
    const [event] = relays.writes.map((w) => w.event);
    assert.equal(relays.writes[1].event, event, 'one signed event, written to both');
    assert.ok(verifyEvent(event));
    assert.equal(event.pubkey, getPublicKey(secretKey));
    assert.equal(event.created_at, NOW);

    assert.equal(report.event_id, event.id);
    assert.equal(report.address, grantAddress(getPublicKey(secretKey), FIXTURE_INPUTS.workloadId));
    assert.equal(report.address, `30438:${getPublicKey(secretKey)}:${FIXTURE_INPUTS.workloadId}`);
    assert.deepEqual(report.accepted, ['ws://relay-a:7100', 'ws://relay-b:7100']);
    assert.deepEqual(report.failed, {});
    assert.deepEqual(report.grant, { ...GRANT.content, name: 'blog' });
    assert.deepEqual(report.event, event);
  });

  it('reports a relay that refused beside the ones that accepted, and never throws for one', async () => {
    const writeTo = async (relay) =>
      relay === 'ws://down:7100' ? 'g.toon.relay refused by g.hub: F02 no route' : null;

    const report = await publishGrant({
      grant: FIXTURE_INPUTS,
      secretKey: TENANT_KEY,
      relays: ['ws://up:7100', 'ws://down:7100'],
      writeTo,
      now: () => NOW,
    });

    assert.deepEqual(report.accepted, ['ws://up:7100']);
    assert.deepEqual(report.failed, { 'ws://down:7100': 'g.toon.relay refused by g.hub: F02 no route' });
  });

  it('a writer that throws is a failed relay too, with its reason', async () => {
    const report = await publishGrant({
      grant: FIXTURE_INPUTS,
      secretKey: TENANT_KEY,
      relays: ['ws://gone:7100'],
      writeTo: async () => {
        throw new Error('ECONNREFUSED');
      },
      now: () => NOW,
    });

    assert.deepEqual(report.accepted, []);
    assert.deepEqual(report.failed, { 'ws://gone:7100': 'ECONNREFUSED' });
  });

  it('refuses to publish to no relay at all rather than signing for nobody', async () => {
    await assert.rejects(
      publishGrant({ grant: FIXTURE_INPUTS, secretKey: TENANT_KEY, relays: [], writeTo: neverSigns, sign: neverSigns, now: () => NOW }),
      /no relay/,
    );
  });
});

describe('renewal and rotation are the same act as publishing', () => {
  // The grant is addressable on `d = <workload_id>`, so a later event under
  // the same tenant and workload id REPLACES the earlier one on a relay
  // (spec §3.1.3). Nothing here is a second mechanism: the tool has no
  // "renew" and no "rotate", only "publish again".
  const publishedAs = async (overrides, createdAt) => {
    const relays = acceptingRelays();
    return publishGrant({
      grant: inputs(overrides),
      secretKey: TENANT_KEY,
      relays: ['ws://relay:7100'],
      writeTo: relays.writeTo,
      now: () => createdAt,
    });
  };

  it('publishing again with a later expiry renews: same address, later expires_at', async () => {
    const first = await publishedAs({}, NOW);
    const renewed = await publishedAs({ expiresAt: FIXTURE_INPUTS.expiresAt + 86_400 }, NOW + 60);

    assert.equal(renewed.address, first.address);
    assert.deepEqual(renewed.event.tags[0], first.event.tags[0], 'the same `d`, so the relay keeps only the newer');
    assert.equal(renewed.grant.expires_at, FIXTURE_INPUTS.expiresAt + 86_400);
    assert.equal(renewed.grant.gateway, first.grant.gateway);
    assert.ok(renewed.event.created_at > first.event.created_at);
  });

  it('publishing again with another gateway rotates: same address, another `p` tag', async () => {
    const other = getPublicKey(generateSecretKey());
    const first = await publishedAs({}, NOW);
    const rotated = await publishedAs({ gateway: other }, NOW + 60);

    assert.equal(rotated.address, first.address);
    assert.deepEqual(rotated.event.tags[0], first.event.tags[0]);
    assert.deepEqual(rotated.event.tags[1], ['p', other]);
    assert.equal(rotated.grant.gateway, other);
  });
});

describe('the provider side, read from the fixtures the provider generated over these same bytes', () => {
  const granted = fixture('status.granted.json');
  const running = fixture('status.running.json');
  const badGrant = fixture('error.bad_grant.json');

  /** What this tool signs for the fixture inputs, with the fixture generator's zero aux randomness. */
  const produced = () => signGrant(grantEvent(FIXTURE_INPUTS, NOW), TENANT_KEY, { auxRand: ZERO_AUX });

  it('a status request carrying exactly what this tool produced was answered 200, and with the tenant\'s own answer', () => {
    const request = granted.request_body.request;
    const content = JSON.parse(request.content);

    assert.deepEqual(content.grant, produced(), 'the request carries this tool\'s event, unchanged');
    assert.equal(request.pubkey, constants.gateway.public_key, 'signed by the gateway, not the tenant');
    assert.equal(content.workload_id, FIXTURE_INPUTS.workloadId);
    assert.equal(granted.response_status, 200);
    assert.deepEqual(granted.response_body, running.response_body, 'exactly what status.running told the tenant');
    assert.equal(granted.response_body.state, 'running');
    assert.ok(
      granted.response_body.access.ports.some((p) => p.container_port === FIXTURE_INPUTS.httpPort),
      'the http_port the grant names is one the provider exposes',
    );
  });

  it('the same request with a grant this tool would not have signed is refused bad_grant', () => {
    // error.bad_grant.json: the same grant, signed by another key. The tool
    // cannot produce this — it signs with the key it is given, and this is
    // the one defect a tenant tool cannot check for — so the fixture is the
    // provider's word that the refusal is `bad_grant`, one code for every
    // defect including an expiry that has passed (spec §6.5; and
    // tests/gateway_grant.rs drives the expiry over this very fixture).
    const request = badGrant.request_body.request;
    const content = JSON.parse(request.content);

    assert.equal(content.grant.content, produced().content, 'the same content this tool signs');
    assert.notEqual(content.grant.pubkey, constants.tenant.public_key);
    assert.equal(badGrant.response_status, 403);
    assert.equal(badGrant.response_body.error, 'bad_grant');
  });
});

describe('the command line', () => {
  it('reads unix seconds or a duration for the expiry', () => {
    assert.equal(parseExpiry({ expiresAt: '1700086400' }, NOW), 1_700_086_400);
    assert.equal(parseExpiry({ expiresIn: '24h' }, NOW), NOW + 86_400);
    assert.equal(parseExpiry({ expiresIn: '90m' }, NOW), NOW + 5_400);
    assert.equal(parseExpiry({ expiresIn: '7d' }, NOW), NOW + 7 * 86_400);
    assert.equal(parseExpiry({ expiresIn: '3600' }, NOW), NOW + 3_600);
    assert.throws(() => parseExpiry({}, NOW), /an expiry is required: --expires-at .* or --expires-in/);
    assert.throws(() => parseExpiry({ expiresAt: '1', expiresIn: '1h' }, NOW), /not both/);
    assert.throws(() => parseExpiry({ expiresIn: 'soon' }, NOW), /--expires-in "soon"/);
  });

  it('reads the spawn\'s container ports as a list', () => {
    assert.deepEqual(parsePorts('443'), [443]);
    assert.deepEqual(parsePorts('80, 443,22'), [80, 443, 22]);
    assert.throws(() => parsePorts('80,http'), /--ports .*"http"/);
    assert.throws(() => parsePorts(undefined), /--ports is required/);
  });

  it('assembles the grant from flags and the environment, relays defaulting to every write route', () => {
    const options = optionsFrom(
      {
        workload: FIXTURE_INPUTS.workloadId,
        gateway: FIXTURE_INPUTS.gateway,
        'http-port': '443',
        ports: '443,22',
        standby: [constants.provider.public_key, constants.standby_provider.public_key],
        'expires-in': '24h',
        name: 'blog',
      },
      {
        TOON_TENANT_KEY: constants.tenant.secret_key,
        RELAY_WRITE_ROUTES: '{"ws://relay:7100":"g.toon.relay","ws://other:7100":"g.other.relay"}',
      },
      NOW,
    );

    assert.deepEqual(options.grant, {
      workloadId: FIXTURE_INPUTS.workloadId,
      gateway: FIXTURE_INPUTS.gateway,
      httpPort: 443,
      ports: [443, 22],
      standbySet: [constants.provider.public_key, constants.standby_provider.public_key],
      expiresAt: NOW + 86_400,
      name: 'blog',
    });
    assert.deepEqual(options.relays, ['ws://relay:7100', 'ws://other:7100']);
    assert.deepEqual(options.secretKey, TENANT_KEY);
  });

  it('takes --relay over the routes\' keys, and --key over the environment', () => {
    const options = optionsFrom(
      {
        workload: FIXTURE_INPUTS.workloadId,
        gateway: FIXTURE_INPUTS.gateway,
        'http-port': '443',
        ports: '443',
        standby: [constants.provider.public_key],
        'expires-at': String(FIXTURE_INPUTS.expiresAt),
        relay: ['ws://mine:7100'],
        key: constants.other_tenant.secret_key,
      },
      { TOON_TENANT_KEY: constants.tenant.secret_key, RELAY_WRITE_ROUTES: '{"ws://relay:7100":"g.toon.relay"}' },
      NOW,
    );

    assert.deepEqual(options.relays, ['ws://mine:7100']);
    assert.deepEqual(options.secretKey, Uint8Array.from(Buffer.from(constants.other_tenant.secret_key, 'hex')));
    assert.equal(options.grant.name, undefined);
  });

  it('refuses a missing or malformed tenant key without looking at anything else', () => {
    const flags = { workload: FIXTURE_INPUTS.workloadId, gateway: FIXTURE_INPUTS.gateway, 'http-port': '443', ports: '443', standby: ['x'], 'expires-in': '1h' };
    assert.throws(() => optionsFrom(flags, {}, NOW), /tenant key is required: --key <64 hex> or TOON_TENANT_KEY/);
    assert.throws(() => optionsFrom({ ...flags, key: 'nsec1abc' }, {}, NOW), /tenant key .*64 hex/);
  });
});
