// The handover tool (`handover.mjs`), which needs no network, no chain and no
// mnemonic: what it derives, what it seals, what it refuses before sealing,
// and that what it derives is the same bytes the provider was proven against.
// Run with `npm test` in this directory.
//
// The proof is against the REAL thing, not against this tool: the wire
// fixtures under ../../tests/fixtures/wire/ were generated by the provider's
// own derivation and HTTP surface over a fixed root secret and a fixed clock
// (`tests/wire_fixtures.rs`). Re-deriving the vectors here, and matching the
// `continuation` a delegated `status` was answered 200 with, is what makes "a
// provider accepts what this tool produced" a fact about
// `status.delegated.json` and not an assumption.

import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

import {
  CONTINUATION_DOMAIN,
  GATEWAY_DOMAIN,
  checkHandover,
  continuationFor,
  gatewaySub,
  handOver,
  handoverFor,
  optionsFrom,
  parseExpiry,
  parsePorts,
  sealKeyBytes,
  sealedSender,
  withdraw,
  withdrawalFor,
} from './handover.mjs';

// ── the fixed world the fixtures were generated in ─────────────────────────

const FIXTURES = new URL('../../tests/fixtures/wire/', import.meta.url);
const fixture = (name) => JSON.parse(readFileSync(new URL(name, FIXTURES), 'utf8'));

const constants = fixture('constants.json');
const CONTINUATION = fixture('continuation.vector.json');
const GATEWAY_SUB = fixture('gateway_sub.vector.json');
const DELEGATED = fixture('status.delegated.json');
const RUNNING = fixture('status.running.json');
const NOW = constants.now;

/** The fixture handover's inputs, exactly as a tenant would hand them to the tool. */
const FIXTURE_INPUTS = {
  rootSecret: constants.tenant.root_secret,
  workloadId: DELEGATED.request_body.request.content.workload_id,
  standbySet: [constants.provider.public_key],
  httpPort: 443,
  expiresAt: DELEGATED.request_body.request.content.gateway_expires_at,
};

/** A fresh, valid set of inputs for the cases that vary one thing. */
const inputs = (overrides = {}) => ({ ...FIXTURE_INPUTS, ...overrides });

/**
 * The grant a message carries for `provider`, read the way a gateway reads
 * it: out of that member's own entry in `standby_set` (spec §12.1).
 *
 * A member the message does not name FAILS here rather than answering
 * nothing, so that a missing member is never reported as a wrong grant.
 */
const grantAt = (message, provider) => {
  const member = message.standby_set.find((entry) => entry.provider === provider);
  assert.ok(member, `the message names no member ${provider}: ${JSON.stringify(message.standby_set)}`);
  return member.grant;
};

/** A gateway's connector as a tenant is given it: the route it terminates and its pinned sealing key. */
const GATEWAY = {
  route: 'g.toon.workload-gateway.handover',
  // A 65-byte uncompressed secp256k1 key, the shape a connector's `GET /ilp`
  // reports and a Profile pins (ADR 0011). Synthetic: the generator point.
  sealKey:
    '0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8',
};

/** A sender that accepts everything it is asked to carry, and remembers each packet. */
const acceptingGateway = () => {
  const sent = [];
  return {
    sent,
    send: async (destination, body) => {
      sent.push({ destination, body });
      return null;
    },
  };
};

/** A sender that must never be reached: the refusal comes first. */
const neverSends = async () => {
  throw new Error('sent a handover that should have been refused before sealing');
};

describe('the derivation', () => {
  it('uses the info prefixes the vectors document, not strings of its own', () => {
    assert.equal(CONTINUATION_DOMAIN, CONTINUATION.info_prefix);
    assert.equal(GATEWAY_DOMAIN, GATEWAY_SUB.info_prefix);
  });

  it('derives the continuation.vector token from the fixture root secret, at both providers', () => {
    assert.equal(
      continuationFor(CONTINUATION.root_secret, CONTINUATION.provider_public_key),
      CONTINUATION.continuation,
    );
    assert.equal(
      continuationFor(CONTINUATION.root_secret, CONTINUATION.at_other_provider.provider_public_key),
      CONTINUATION.at_other_provider.continuation,
    );
    assert.equal(
      continuationFor(constants.other_tenant.root_secret, constants.provider.public_key),
      constants.other_tenant.continuation_at_provider,
    );
  });

  it('derives the gateway_sub.vector grant from the token, and a different one a second later', () => {
    assert.equal(gatewaySub(GATEWAY_SUB.continuation, GATEWAY_SUB.expires_at), GATEWAY_SUB.gateway_sub);
    assert.equal(
      gatewaySub(GATEWAY_SUB.continuation, GATEWAY_SUB.at_the_next_second.expires_at),
      GATEWAY_SUB.at_the_next_second.gateway_sub,
    );
  });
});

describe('the handover a run produces', () => {
  it('carries the grant a provider answered a delegated status with — status.delegated, byte for byte', () => {
    const handover = handoverFor(FIXTURE_INPUTS, NOW);
    const request = DELEGATED.request_body.request;

    // What the gateway presents as its request's `continuation`, and the
    // moment it names in `gateway_expires_at`, are this tool's output.
    assert.equal(grantAt(handover, constants.provider.public_key), request.continuation);
    assert.equal(handover.expires_at, request.content.gateway_expires_at);
    assert.equal(handover.workload_id, request.content.workload_id);
    // And the provider's own HTTP surface answered that request 200, with
    // exactly what it told the tenant.
    assert.equal(DELEGATED.response_status, 200);
    assert.deepEqual(DELEGATED.response_body, RUNNING.response_body);
    assert.ok(
      DELEGATED.response_body.access.ports.some((p) => p.container_port === handover.http_port),
      'the http_port the handover names is one the provider exposes',
    );
  });

  it('carries what the gateway needs and nothing else: the removed event\'s content, less the tenant', () => {
    const handover = handoverFor(inputs({ name: 'blog' }), NOW);
    assert.deepEqual(Object.keys(handover), ['workload_id', 'standby_set', 'http_port', 'expires_at', 'name']);
    assert.deepEqual(Object.keys(handover.standby_set[0]), ['provider', 'grant']);
    assert.deepEqual(handover.standby_set.map((member) => member.provider), [constants.provider.public_key]);
    assert.equal(handover.http_port, 443);
    assert.equal(handover.name, 'blog');
    assert.equal('name' in handoverFor(FIXTURE_INPUTS, NOW), false, 'no name, no field');
  });

  it('carries each member with the grant derived for its own key, primary first, because the token it derives from is per provider', () => {
    const members = [constants.primary_provider.public_key, constants.standby_provider.public_key];
    const handover = handoverFor(inputs({ standbySet: members }), NOW);

    // Each entry is a member and the grant derived under that member's own
    // key, in the set's order — which is the order a gateway asks them in.
    assert.deepEqual(
      handover.standby_set,
      members.map((member) => ({
        provider: member,
        grant: gatewaySub(continuationFor(FIXTURE_INPUTS.rootSecret, member), FIXTURE_INPUTS.expiresAt),
      })),
    );
    assert.notEqual(
      handover.standby_set[0].grant,
      handover.standby_set[1].grant,
      'one member cannot read at another',
    );
  });

  it('derives rather than stores: the same root secret and moment give the same grant; a later moment another', () => {
    const first = handoverFor(FIXTURE_INPUTS, NOW);
    const again = handoverFor(FIXTURE_INPUTS, NOW + 1000);
    assert.deepEqual(again, first, 'nothing about a run but its inputs decides the grant');

    const later = handoverFor(inputs({ expiresAt: FIXTURE_INPUTS.expiresAt + 86_400 }), NOW);
    assert.notEqual(grantAt(later, constants.provider.public_key), grantAt(first, constants.provider.public_key));
    assert.equal(later.expires_at, FIXTURE_INPUTS.expiresAt + 86_400);
  });
});

describe('what a provider or a gateway would trip on is refused here first, before anything is sealed', () => {
  const refusal = async (overrides, pattern, gateway = GATEWAY) => {
    await assert.rejects(
      handOver({ handover: inputs(overrides), gateway, send: neverSends, now: () => NOW }),
      pattern,
    );
  };

  it('an expiry already past, naming the expiry and the clock', async () => {
    await refusal({ expiresAt: NOW - 1 }, /expires_at 1699999999 is already past \(now 1700000000\)/);
    await refusal({ expiresAt: NOW }, /expires_at 1700000000 is now: .*expired by the time a Workload Gateway held it/);
    await refusal({ expiresAt: 'tomorrow' }, /expires_at must be unix seconds/);
  });

  it('a root secret that is not 64 lowercase hex, without quoting it back', async () => {
    for (const bad of ['AB'.repeat(32), 'ab', undefined, 'nsec1abc']) {
      await assert.rejects(
        handOver({ handover: inputs({ rootSecret: bad }), gateway: GATEWAY, send: neverSends, now: () => NOW }),
        (e) => {
          assert.match(e.message, /root secret must be 64 lowercase hex/);
          if (typeof bad === 'string') assert.equal(e.message.includes(bad), false, 'the secret is not in the message');
          return true;
        },
      );
    }
  });

  it('a Standby Set member that is not a public key, one named twice, or no Standby Set at all', async () => {
    await refusal({ standbySet: [] }, /Standby Set must name at least one provider, the primary first/);
    await refusal({ standbySet: [constants.provider.public_key, 'not-a-key'] }, /Standby Set member 2 .*"not-a-key".*64 hex/);
    await refusal({ standbySet: ['ABCD'.repeat(16)] }, /Standby Set member 1 .*lowercase/);
    await refusal({ standbySet: [constants.provider.public_key, constants.provider.public_key] }, /names one provider twice/);
  });

  it('an http_port that is not a port, or not one of the ports the tenant asked for when those are given', async () => {
    await refusal({ httpPort: 8080, ports: [443, 22] }, /http_port 8080 is not one of the spawn's container ports \(443, 22\)/);
    await refusal({ httpPort: 0 }, /http_port .*1 and 65535/);
    await refusal({ httpPort: '443' }, /http_port .*1 and 65535/);
    assert.equal(checkHandover(inputs({ httpPort: 443, ports: [443, 22] }), NOW), null);
  });

  it('a name that is not a single DNS label, saying which rule it breaks', async () => {
    await refusal({ name: 'my.blog' }, /name "my.blog".*single DNS label.*no dots/);
    await refusal({ name: 'Blog' }, /name "Blog".*lowercase/);
    await refusal({ name: '-blog' }, /name "-blog".*hyphen/);
    await refusal({ name: 'my_blog' }, /name "my_blog".*letters, digits and hyphens/);
    await refusal({ name: '' }, /name "".*empty/);
    await refusal({ name: 'a'.repeat(64) }, /name .*63/);
  });

  it('a workload id that is not 64 lowercase hex characters', async () => {
    await refusal({ workloadId: 'AA'.repeat(32) }, /workload id .*lowercase hex/);
    await refusal({ workloadId: 'aa' }, /workload id .*64/);
  });

  it('a gateway connector with no route, or a sealing key that is not a secp256k1 point', async () => {
    await refusal({}, /gateway route is required/, { ...GATEWAY, route: undefined });
    await refusal({}, /gateway route "g toon".*ILP address/, { ...GATEWAY, route: 'g toon' });
    await refusal({}, /sealing key is required/, { ...GATEWAY, sealKey: undefined });
    await refusal({}, /sealing key .*65-byte uncompressed .*or 33-byte compressed/, { ...GATEWAY, sealKey: 'ab'.repeat(32) });
    await refusal({}, /sealing key .*65-byte uncompressed .*or 33-byte compressed/, { ...GATEWAY, sealKey: '05' + 'ab'.repeat(64) });
  });

  it('and `checkHandover` is the same rule on its own, for a caller that only wants the verdict', () => {
    assert.equal(checkHandover(FIXTURE_INPUTS, NOW), null);
    assert.match(checkHandover(inputs({ expiresAt: NOW - 1 }), NOW), /already past/);
    assert.match(checkHandover(inputs({ name: 'A' }), NOW), /lowercase/);
  });
});

describe('handing over', () => {
  it('seals one handover to the gateway\'s route and reports it delivered, with the handover as sent', async () => {
    const gateway = acceptingGateway();

    const report = await handOver({ handover: inputs({ name: 'blog' }), gateway: GATEWAY, send: gateway.send, now: () => NOW });

    assert.equal(gateway.sent.length, 1, 'one packet');
    const [{ destination, body }] = gateway.sent;
    assert.equal(destination, GATEWAY.route);
    assert.deepEqual(body, { handover: handoverFor(inputs({ name: 'blog' }), NOW) }, 'the body is the handover under one key');
    assert.deepEqual(report, {
      workload_id: FIXTURE_INPUTS.workloadId,
      gateway: { route: GATEWAY.route, seal_key: GATEWAY.sealKey },
      handover: body.handover,
      delivered: true,
    });
  });

  it('reports a gateway that refused, or a path that dropped the packet, and never throws for either', async () => {
    const refused = await handOver({
      handover: FIXTURE_INPUTS,
      gateway: GATEWAY,
      send: async () => 'g.toon.workload-gateway.handover refused by destination: F00 no such workload',
      now: () => NOW,
    });
    assert.equal(refused.delivered, false);
    assert.equal(refused.failed, 'g.toon.workload-gateway.handover refused by destination: F00 no such workload');
    assert.ok(
      grantAt(refused.handover, constants.provider.public_key),
      'the handover is still reported, so a tenant can see what it derived',
    );

    const dropped = await handOver({
      handover: FIXTURE_INPUTS,
      gateway: GATEWAY,
      send: async () => {
        throw new Error('ECONNREFUSED');
      },
      now: () => NOW,
    });
    assert.equal(dropped.delivered, false);
    assert.equal(dropped.failed, 'ECONNREFUSED');
  });

  it('the pinned key is what the sender seals to, as bytes, uncompressed or compressed', () => {
    assert.equal(sealKeyBytes(GATEWAY.sealKey).length, 65);
    assert.equal(sealKeyBytes(GATEWAY.sealKey)[0], 0x04);
    assert.equal(sealKeyBytes('02' + '79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798').length, 33);
  });
});

describe('withdrawing', () => {
  /** What a tenant holds when it withdraws: the lease, the set, and the moment it handed over for. */
  const WITHDRAWAL_INPUTS = {
    rootSecret: FIXTURE_INPUTS.rootSecret,
    workloadId: FIXTURE_INPUTS.workloadId,
    standbySet: FIXTURE_INPUTS.standbySet,
    expiresAt: FIXTURE_INPUTS.expiresAt,
  };

  it('names the workload and bears the grant currently in force — the one the handover carried, re-derived', () => {
    const withdrawal = withdrawalFor(WITHDRAWAL_INPUTS);
    const handover = handoverFor(FIXTURE_INPUTS, NOW);

    assert.deepEqual(Object.keys(withdrawal), ['workload_id', 'expires_at', 'standby_set']);
    assert.equal(withdrawal.workload_id, FIXTURE_INPUTS.workloadId);
    assert.equal(withdrawal.expires_at, FIXTURE_INPUTS.expiresAt);
    assert.deepEqual(
      withdrawal.standby_set,
      handover.standby_set,
      'member for member, the same grants: the same root secret and the same moment, and the same encoding as a handover',
    );
    assert.equal(grantAt(withdrawal, constants.provider.public_key), DELEGATED.request_body.request.continuation);
  });

  it('seals one withdrawal to the gateway\'s route and reports it delivered', async () => {
    const gateway = acceptingGateway();

    const report = await withdraw({ withdrawal: WITHDRAWAL_INPUTS, gateway: GATEWAY, send: gateway.send });

    assert.equal(gateway.sent.length, 1);
    assert.equal(gateway.sent[0].destination, GATEWAY.route);
    assert.deepEqual(gateway.sent[0].body, { withdrawal: withdrawalFor(WITHDRAWAL_INPUTS) });
    assert.deepEqual(report, {
      workload_id: FIXTURE_INPUTS.workloadId,
      gateway: { route: GATEWAY.route, seal_key: GATEWAY.sealKey },
      withdrawal: gateway.sent[0].body.withdrawal,
      delivered: true,
    });
  });

  it('is refused before sealing for the same lease defects a handover is, and for a moment that is not one', async () => {
    const refusal = (overrides, pattern) =>
      assert.rejects(withdraw({ withdrawal: { ...WITHDRAWAL_INPUTS, ...overrides }, gateway: GATEWAY, send: neverSends }), pattern);
    await refusal({ rootSecret: 'xyz' }, /root secret must be 64 lowercase hex/);
    await refusal({ workloadId: 'aa' }, /workload id .*64/);
    await refusal({ standbySet: [] }, /Standby Set must name at least one provider/);
    await refusal({ expiresAt: '1700086400' }, /expires_at must be unix seconds/);
    await assert.rejects(
      withdraw({ withdrawal: WITHDRAWAL_INPUTS, gateway: { ...GATEWAY, sealKey: 'nope' }, send: neverSends }),
      /sealing key/,
    );
  });

  it('bears a grant whose moment has passed all the same: it ends serving, and the gateway compares it against what it holds', () => {
    // A withdrawal is not checked against a provider — the gateway compares
    // the value against the grant it was handed — so the moment is whatever
    // the handover named, past or not. Nothing here is revocation: the grant
    // it bears reads the lease until that moment whether or not it is sent.
    const withdrawal = withdrawalFor({ ...WITHDRAWAL_INPUTS, expiresAt: NOW - 86_400 });
    assert.equal(withdrawal.expires_at, NOW - 86_400);
  });
});

describe('the command line', () => {
  /** What both subcommands take: the lease, the set, and the gateway's connector. */
  const LEASE = {
    workload: FIXTURE_INPUTS.workloadId,
    standby: [constants.primary_provider.public_key, constants.standby_provider.public_key],
    'gateway-route': GATEWAY.route,
    'gateway-seal-key': GATEWAY.sealKey,
  };
  const FLAGS = { ...LEASE, 'http-port': '443' };

  it('reads unix seconds or a duration for the expiry', () => {
    assert.equal(parseExpiry({ expiresAt: '1700086400' }, NOW), 1_700_086_400);
    assert.equal(parseExpiry({ expiresIn: '24h' }, NOW), NOW + 86_400);
    assert.equal(parseExpiry({ expiresIn: '90m' }, NOW), NOW + 5_400);
    assert.equal(parseExpiry({ expiresIn: '7d' }, NOW), NOW + 7 * 86_400);
    assert.equal(parseExpiry({ expiresIn: '3600' }, NOW), NOW + 3_600);
    assert.throws(() => parseExpiry({}, NOW), /an expiry is required: --expires-at .* or --expires-in/);
    assert.throws(() => parseExpiry({ expiresAt: '1', expiresIn: '1h' }, NOW), /not both/);
    assert.throws(() => parseExpiry({ expiresIn: 'soon' }, NOW), /--expires-in "soon"/);
  });

  it('reads the spawn\'s container ports as a list, when given', () => {
    assert.deepEqual(parsePorts('443'), [443]);
    assert.deepEqual(parsePorts('80, 443,22'), [80, 443, 22]);
    assert.equal(parsePorts(undefined), undefined);
    assert.throws(() => parsePorts('80,http'), /--ports .*"http"/);
  });

  it('assembles a handover from flags and the environment, the root secret from TOON_ROOT_SECRET', () => {
    const options = optionsFrom(
      'handover',
      { ...FLAGS, ports: '443,22', 'expires-in': '24h', name: 'blog' },
      { TOON_ROOT_SECRET: constants.tenant.root_secret },
      NOW,
    );
    assert.deepEqual(options, {
      handover: {
        rootSecret: constants.tenant.root_secret,
        workloadId: FIXTURE_INPUTS.workloadId,
        standbySet: FLAGS.standby,
        httpPort: 443,
        ports: [443, 22],
        expiresAt: NOW + 86_400,
        name: 'blog',
      },
      gateway: { route: GATEWAY.route, sealKey: GATEWAY.sealKey },
    });
  });

  it('assembles a withdrawal, whose moment is only ever --expires-at: the one the handover named', () => {
    const options = optionsFrom(
      'withdrawal',
      { ...LEASE, 'expires-at': String(FIXTURE_INPUTS.expiresAt), 'root-secret': constants.other_tenant.root_secret },
      { TOON_ROOT_SECRET: constants.tenant.root_secret },
      NOW,
    );
    assert.deepEqual(options, {
      withdrawal: {
        rootSecret: constants.other_tenant.root_secret,
        workloadId: FIXTURE_INPUTS.workloadId,
        standbySet: FLAGS.standby,
        expiresAt: FIXTURE_INPUTS.expiresAt,
      },
      gateway: { route: GATEWAY.route, sealKey: GATEWAY.sealKey },
    });
    assert.throws(
      () => optionsFrom('withdrawal', { ...LEASE, 'expires-in': '1h', 'root-secret': constants.tenant.root_secret }, {}, NOW),
      /a withdrawal names the moment the handover named: --expires-at <unix seconds>, not --expires-in/,
    );
  });

  it('refuses a handover\'s flags on a withdrawal by name, rather than dropping them quietly', () => {
    const withdrawal = { ...LEASE, 'expires-at': String(FIXTURE_INPUTS.expiresAt) };
    for (const [flag, value] of [
      ['http-port', '443'],
      ['ports', '443,22'],
      ['name', 'blog'],
    ]) {
      assert.throws(
        () => optionsFrom('withdrawal', { ...withdrawal, [flag]: value }, { TOON_ROOT_SECRET: constants.tenant.root_secret }, NOW),
        new RegExp(`--${flag} is a handover's`),
        `--${flag} on a withdrawal`,
      );
    }
  });

  it('refuses a missing root secret without looking at anything else, and refuses to be given a key', () => {
    assert.throws(() => optionsFrom('handover', FLAGS, {}, NOW), /a root secret is required: --root-secret <64 hex> or TOON_ROOT_SECRET/);
    assert.throws(() => optionsFrom('handover', FLAGS, { TOON_ROOT_SECRET: 'nsec1abc' }, NOW), (e) => {
      assert.match(e.message, /root secret .*64 lowercase hex/);
      assert.equal(e.message.includes('nsec1abc'), false);
      return true;
    });
    // A tenant key is not an input this tool has: it derives, it never signs.
    assert.throws(
      () => optionsFrom('handover', FLAGS, { TOON_TENANT_KEY: constants.provider.secret_key }, NOW),
      /a root secret is required/,
    );
  });

  it('knows exactly two subcommands', () => {
    assert.throws(() => optionsFrom('publish', FLAGS, { TOON_ROOT_SECRET: constants.tenant.root_secret }, NOW), /handover, withdrawal or rotate/);
  });
});

describe('the sender seal.mjs fills the seam with', () => {
  /** A client that answers `answer` and remembers the one call it was given. */
  const clientAnswering = (answer) => {
    const calls = [];
    return {
      calls,
      send: async (destination, request, options) => {
        calls.push({ destination, request, options });
        return answer;
      },
    };
  };

  const fulfilled = (status, text) => ({ fulfilled: true, status, text: () => text, json: () => JSON.parse(text) });

  it('seals the body to the gateway\'s PINNED key, as bytes, and sends it to the route', async () => {
    const client = clientAnswering(fulfilled(200, '{"accepted":true}'));
    const message = { handover: handoverFor(FIXTURE_INPUTS, NOW) };

    assert.equal(await sealedSender(client, GATEWAY.sealKey)(GATEWAY.route, message), null);

    assert.equal(client.calls.length, 1);
    const [{ destination, request, options }] = client.calls;
    assert.equal(destination, GATEWAY.route);
    assert.deepEqual(request, { body: message }, 'the message is the body, and the client encodes it');
    assert.deepEqual(options.sealTo, sealKeyBytes(GATEWAY.sealKey), 'sealed to the pinned key itself');
    assert.ok(options.sealTo instanceof Uint8Array, 'as bytes: nothing is fetched to learn the key');
  });

  it('says why when the packet never reached the gateway, and when the gateway answered something else', async () => {
    const refused = clientAnswering({ fulfilled: false, refusedBy: 'g.toon', code: 'F02', message: 'no route' });
    assert.equal(
      await sealedSender(refused, GATEWAY.sealKey)(GATEWAY.route, {}),
      `${GATEWAY.route} refused by g.toon: F02 no route`,
    );

    const answered = clientAnswering(fulfilled(404, 'no such workload'));
    assert.equal(
      await sealedSender(answered, GATEWAY.sealKey)(GATEWAY.route, {}),
      `${GATEWAY.route} answered HTTP 404: no such workload`,
    );
  });
});
