#!/usr/bin/env bash
# Render the files that carry deployment-specific values.
#
#   provider.toml.template    -> provider.toml              (0600 — A SECRET)
#     + the listings file (LISTINGS_FILE, default listings.toml)
#   connector.toml.template   -> connector.toml             (paths, no secrets)
#     + [[routes]] generated by `toon-provider routes` on that provider.toml
#   .env OPERATOR_BEARER_TOKEN-> operator-bearer.token       (0600 — a secret)
#   .env OPERATOR_WRITE_KEY   -> operator-write.keys         (0600 — public keys)
#   nginx/node.conf.template  -> nginx/conf.d/node.conf
#
# Every output is gitignored, and so are its inputs: .env and the listings
# file are the operator's own. Nothing an operator makes theirs is a committed
# file, so a box runs from an unmodified checkout and auto-apply.sh can
# fast-forward it (it stops on a dirty tree).
#
# ── Where `toon-provider` comes from ────────────────────────────────────────
# The connector's [[routes]] are not written by anyone: they are what
# `toon-provider routes` prints for the provider.toml rendered here, so a
# price is written once and the two files cannot drift. On a box the binary
# is the provider image this compose file runs, pulled or built first so the
# rows come from the same build that will serve them, and run with
# `docker run` rather than `docker compose run`: the service's own bind mount
# names ./provider.toml, which --connector-only has not rendered, and docker
# answers a missing bind source by creating a directory there. It also mounts
# the live lease table read-only when there is one, because a retired listing
# version keeps its rows only while a lease still runs on it (ADR 0009).
#
# Off a box, or in tests, set TOON_PROVIDER_BIN to a built binary instead:
#
#   TOON_PROVIDER_BIN=../target/release/toon-provider ./render.sh
#
#   ./render.sh                  everything
#   ./render.sh --connector-only everything EXCEPT provider.toml
#
# The second mode exists for one moment in bootstrap.sh: provider.toml cannot
# be rendered until the connector has said what its sealing key is, and the
# connector cannot say until it is running. So the connector's own files are
# rendered first, it is started alone, asked, and then everything is rendered
# properly. That is ONE renderer with two scopes rather than two renderers --
# the thing this script knows that a hand-rolled copy in bootstrap.sh kept
# forgetting is that the key files need their ownership fixed too.
#
# envsubst is given an EXPLICIT variable list. Without one it would substitute
# every $NAME it sees, and the nginx template contains nginx variables ($host,
# $upstream, $binary_remote_addr) that must survive to the rendered file.
set -euo pipefail
cd "$(dirname "$0")"

CONNECTOR_ONLY=0
case "${1:-}" in
  --connector-only) CONNECTOR_ONLY=1 ;;
  '') ;;
  *) echo "usage: ./render.sh [--connector-only]" >&2; exit 2 ;;
esac

[ -f .env ] || { echo "Missing .env — copy .env.example and fill it in." >&2; exit 1; }
set -a; . ./.env; set +a

: "${DOMAIN:?set DOMAIN in .env}"
: "${PROVIDER_NAME:?set PROVIDER_NAME in .env}"
: "${PUBLIC_IP:?set PUBLIC_IP in .env (this box public IPv4 — where tenants reach their workloads)}"
: "${NOSTR_PRIVATE_KEY:?set NOSTR_PRIVATE_KEY in .env (openssl rand -hex 32)}"
: "${RELAY_WS:?set RELAY_WS in .env (the relay READ url this provider publishes to)}"
: "${OPERATOR_BEARER_TOKEN:?set OPERATOR_BEARER_TOKEN in .env (openssl rand -hex 32)}"
: "${OPERATOR_WRITE_KEY:?set OPERATOR_WRITE_KEY in .env (the ed25519 public key allowed to sign operator writes)}"
: "${ILP_ADDRESS:?set ILP_ADDRESS in .env (the ILP address every route of this provider hangs off)}"
: "${SETTLEMENT_EVM_CHAIN_ID:?set SETTLEMENT_EVM_CHAIN_ID in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_EVM_RPC_URL:?set SETTLEMENT_EVM_RPC_URL in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_EVM_REGISTRY:?set SETTLEMENT_EVM_REGISTRY in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_EVM_TOKEN:?set SETTLEMENT_EVM_TOKEN in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_EVM_DECIMALS:?set SETTLEMENT_EVM_DECIMALS in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_SOLANA_RPC_URL:?set SETTLEMENT_SOLANA_RPC_URL in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_SOLANA_PROGRAM_ID:?set SETTLEMENT_SOLANA_PROGRAM_ID in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_SOLANA_TOKEN:?set SETTLEMENT_SOLANA_TOKEN in .env (.env.example has the devnet preset)}"
: "${SETTLEMENT_SOLANA_DECIMALS:?set SETTLEMENT_SOLANA_DECIMALS in .env (.env.example has the devnet preset)}"
: "${CERT_NAME:=proxy.provider.${DOMAIN}}"
export CERT_NAME
LISTINGS_FILE=${LISTINGS_FILE:-listings.toml}

# ── Nobody takes the fleet's namespace by accident ───────────────────────────
# `g.toon` and everything under it are the TOON fleet's own addresses. A
# second provider copying the devnet box's .env would otherwise answer for
# `g.toon.provider` too, and whichever connector a packet reached would take
# payment for the other's routes. The fleet's own boxes say so outright.
case "$ILP_ADDRESS" in
  g.toon | g.toon.*)
    if [ "${TOON_DEVNET_BOX:-0}" != 1 ]; then
      echo "ILP_ADDRESS=${ILP_ADDRESS} is under g.toon., the TOON fleet's own namespace." >&2
      echo "Pick an address of your own (e.g. g.<your-name>.provider). Only the fleet's" >&2
      echo "own boxes set TOON_DEVNET_BOX=1 in .env to use one." >&2
      exit 1
    fi
    ;;
esac

[ -f "$LISTINGS_FILE" ] || {
  echo "Missing the listings file ${LISTINGS_FILE} (LISTINGS_FILE in .env)." >&2
  echo "It is what this provider sells, and it is yours: start from the example," >&2
  echo "  cp listings.example.toml listings.toml" >&2
  echo "and edit it. It is gitignored, so the checkout stays clean." >&2
  exit 1
}

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# ── The sealing key, which nothing here can invent ───────────────────────────
# A tenant seals its spawn to the key this box's connector answers with, and
# refuses to proceed if the Profile names a different one (ADR 0011). So the
# value below is not a setting: it is a COPY of a fact, and the only correct
# way to get it is to read it off the connector.
#
# bootstrap.sh reads it from `GET /ilp/identity` and writes it into .env, so
# nobody transcribes it by hand. Refuse rather than render a Profile that would
# be rejected by every tenant that read it.
if [ "$CONNECTOR_ONLY" = 0 ] && [ -z "${CONNECTOR_SEAL_KEY:-}" ]; then
  echo "CONNECTOR_SEAL_KEY is not set in .env." >&2
  echo >&2
  echo "It is this box's connector's own sealing key, copied verbatim — a tenant" >&2
  echo "compares it byte for byte against GET /ilp/identity before it will spawn" >&2
  echo "anything here (ADR 0011). Start the connector and read it off:" >&2
  echo >&2
  echo "  docker compose up -d provider-connector" >&2
  echo "  curl -s http://127.0.0.1:4000/ilp/identity" >&2
  echo >&2
  echo "then put its .publicKey (WITH the 0x) in .env as CONNECTOR_SEAL_KEY." >&2
  echo "./bootstrap.sh does all of that for you." >&2
  exit 1
fi

# ── A directory where a file belongs ─────────────────────────────────────────
# docker answers a bind mount naming a path that does not exist by CREATING an
# empty directory there. Anything that starts the app before its config is
# rendered leaves one behind, and the app then dies on "read provider config
# at /etc/toon-provider/provider.toml: Is a directory" for the rest of time,
# because envsubst below cannot write over a directory either. An EMPTY one
# can only have come from that, so clear it; a non-empty one is somebody's
# work and is refused instead.
for path in provider.toml connector.toml; do
  [ -d "$path" ] || continue
  if rmdir "$path" 2>/dev/null; then
    echo "note: removed an empty directory at ./${path} — docker creates one when a" >&2
    echo "      bind mount names a file that has not been rendered yet." >&2
  else
    echo "./${path} is a directory and is not empty. It must be a file; something" >&2
    echo "other than this script put it there. Move it aside and re-run." >&2
    exit 1
  fi
done

# ── provider.toml — the one rendered file in this fleet that IS a secret ─────
# It carries `nostr_private_key` inline: the identity that signs this
# provider's Profile, Listings, Liveness and Eviction Notices. Everything else
# here names key files; this one cannot, because the app takes the value.

# Replace the one line that is exactly $1 with the contents of file $2, reading
# stdin to stdout. A template with no marker, or two, is refused: either would
# render a config that silently sells nothing or everything twice.
splice() {
  awk -v marker="$1" -v file="$2" '
    $0 == marker { n++; while ((getline line < file) > 0) print line; close(file); next }
    { print }
    END { if (n != 1) { print "render.sh: expected exactly one \"" marker "\" line" > "/dev/stderr"; exit 3 } }'
}

# $1: the seal key to render with; $2: where to write. The listings are
# spliced in AFTER envsubst so that nothing in the operator's own file is
# ever read as a variable.
render_provider_toml() {
  CONNECTOR_SEAL_KEY=$1 envsubst '${PROVIDER_NAME} ${ILP_ADDRESS} ${PUBLIC_IP} ${NOSTR_PRIVATE_KEY} ${DOMAIN} ${RELAY_WS} ${CONNECTOR_SEAL_KEY} ${SETTLEMENT_EVM_CHAIN_ID} ${SETTLEMENT_EVM_TOKEN} ${SETTLEMENT_EVM_DECIMALS} ${SETTLEMENT_SOLANA_TOKEN} ${SETTLEMENT_SOLANA_DECIMALS}' \
    < provider.toml.template | splice '# @render: listings' "$LISTINGS_FILE" > "$2"
}

# `toon-provider routes` for the provider config at $1, rows only: the
# command's own comment header is dropped, because connector.toml.template
# says where the rows came from and a second, generic account of it would be
# the one nobody updates. See the header of this file for where the binary
# comes from.
provider_routes() {
  if [ -n "${TOON_PROVIDER_BIN:-}" ]; then
    "$TOON_PROVIDER_BIN" --config "$1" routes
  else
    # Whichever the compose file says: a pinned image is pulled, a build is
    # built (a cache hit when nothing changed). The other is a no-op.
    docker compose pull --quiet --ignore-buildable provider >&2
    docker compose build --quiet provider >&2
    local image volume state=()
    image=$(docker compose config --images provider)
    volume=$(docker volume ls -q \
      --filter "label=com.docker.compose.project=${COMPOSE_PROJECT_NAME:-provider}" \
      --filter label=com.docker.compose.volume=provider_state)
    [ -n "$volume" ] && state=(-v "${volume}:/var/lib/toon-provider:ro")
    docker run --rm \
      -v "$(cd "$(dirname "$1")" && pwd)/$(basename "$1"):/etc/toon-provider/provider.toml:ro" \
      "${state[@]}" \
      --entrypoint toon-provider "$image" --config /etc/toon-provider/provider.toml routes
  fi | awk 'rows || !/^#/ { rows = 1; print }'
}

if [ "$CONNECTOR_ONLY" = 0 ]; then
  render_provider_toml "$CONNECTOR_SEAL_KEY" "$WORK/provider.toml"
  ROUTES_FROM=$WORK/provider.toml
else
  # The routes do not depend on the sealing key, but the config loader will
  # not load a publishing provider without one. So --connector-only renders a
  # throwaway copy with a well-formed placeholder, generates the routes from
  # that, and deletes it: ./provider.toml is never written with a key a tenant
  # would refuse. The connector.toml it produces is byte-for-byte the one the
  # full render will, so the later render restarts nothing.
  render_provider_toml "0x$(printf '0%.0s' $(seq 64))" "$WORK/placeholder-provider.toml"
  ROUTES_FROM=$WORK/placeholder-provider.toml
fi

provider_routes "$ROUTES_FROM" > "$WORK/routes.toml"
grep -q '^\[\[routes\]\]$' "$WORK/routes.toml" || {
  echo "\`toon-provider routes\` printed no [[routes]] for ${ROUTES_FROM##*/}; refusing to" >&2
  echo "render a connector that terminates nothing." >&2
  exit 1
}

envsubst '${DOMAIN} ${ILP_ADDRESS} ${SETTLEMENT_EVM_RPC_URL} ${SETTLEMENT_EVM_REGISTRY} ${SETTLEMENT_EVM_TOKEN} ${SETTLEMENT_EVM_DECIMALS} ${SETTLEMENT_SOLANA_RPC_URL} ${SETTLEMENT_SOLANA_PROGRAM_ID} ${SETTLEMENT_SOLANA_TOKEN} ${SETTLEMENT_SOLANA_DECIMALS}' \
  < connector.toml.template | splice '# @render: routes' "$WORK/routes.toml" > "$WORK/connector.toml"

# Written only once everything above has succeeded, so a refusal leaves the
# last good render in place rather than half of a new one.
if [ "$CONNECTOR_ONLY" = 0 ]; then
  cp "$WORK/provider.toml" provider.toml
  chmod 600 provider.toml
fi
cp "$WORK/connector.toml" connector.toml

# ── The operator surface's two credentials ───────────────────────────────────
#   operator-bearer.token   the shared secret that gates operator READS
#   operator-write.keys     the PUBLIC halves allowed to sign operator WRITES,
#                           one ed25519 key per line as 64 hex characters;
#                           `#` starts a comment
printf '%s\n' "${OPERATOR_BEARER_TOKEN}" > operator-bearer.token
{
  echo "# Public keys allowed to sign operator writes, one per line."
  echo "# Rendered from OPERATOR_WRITE_KEY in .env by ./render.sh."
  printf '%s\n' "${OPERATOR_WRITE_KEY}"
} > operator-write.keys

# None of these may be world-readable — but the connector container runs as uid
# 10001, and a root-owned 0600 file is unreadable to it ("failed to read config
# file: Permission denied", then a restart loop). Hand the connector's three to
# that uid rather than widening the mode. provider.toml stays root-owned: the
# provider image runs as root and it is the one file here that must not be
# readable by anything else.
#
# THE HAND-PLACED KEY FILES NEED THE SAME TREATMENT, and the fleet's runbooks
# have always said so as a manual step (connector#492's restart loop:
# "failed to read signer key_file at /app/data/signer.key: Permission denied").
# A step a human has to remember is a step a human forgets, and the failure is
# a container that restarts forever while everything around it looks fine.
# They are chmodded here too, so `openssl rand -hex 32 > signer.key` with a
# default umask is corrected rather than merely tolerated.
chmod 600 connector.toml operator-bearer.token operator-write.keys
for key in signer.key settlement.key settlement-solana.key; do
  [ -f "$key" ] && chmod 600 "$key"
done
if [ "$(id -u)" = 0 ]; then
  chown "${CONNECTOR_UID:-10001}:${CONNECTOR_UID:-10001}" \
    connector.toml operator-bearer.token operator-write.keys
  for key in signer.key settlement.key settlement-solana.key; do
    [ -f "$key" ] && chown "${CONNECTOR_UID:-10001}:${CONNECTOR_UID:-10001}" "$key"
  done
  [ "$CONNECTOR_ONLY" = 0 ] && chown 0:0 provider.toml
else
  echo "note: not running as root, so the rendered files stay owned by $(id -un)." >&2
  echo "      The connector container runs as uid 10001 and will not be able to" >&2
  echo "      read them. Fine for a local render; re-run as root on the box." >&2
fi

mkdir -p nginx/conf.d
envsubst '${DOMAIN} ${CERT_NAME}' \
  < nginx/node.conf.template > nginx/conf.d/node.conf

# ── Does what is sold fit this box? ──────────────────────────────────────────
# Capacity is a promise, not a measurement, and only the operator knows what
# the box holds -- so this WARNS and never refuses. It reads the memory of the
# machine it runs on (the box, when bootstrap.sh or auto-apply.sh runs it) and
# compares it with every listing sold out, leaving about 1 GiB for the five
# containers and the host (README § "Sizing the box" does the arithmetic). A
# retired version still listed is counted too: its last leases hold memory
# until they end.
MEMINFO=${PROC_MEMINFO:-/proc/meminfo}
if [ -r "$MEMINFO" ]; then
  BOX_MIB=$(awk '/^MemTotal:/ { print int($2 / 1024) }' "$MEMINFO")
  SOLD_MIB=$(awk '
    function flush() { total += capacity * memory; capacity = 0; memory = 0 }
    /^[[:space:]]*\[\[listings\]\]/ { flush() }
    /^[[:space:]]*capacity[[:space:]]*=/  { v = $0; sub(/^[^=]*=[[:space:]]*/, "", v); capacity = v + 0 }
    /^[[:space:]]*memory_mb[[:space:]]*=/ { v = $0; sub(/^[^=]*=[[:space:]]*/, "", v); memory = v + 0 }
    END { flush(); print total + 0 }' "$LISTINGS_FILE")
  RESERVE_MIB=1024
  if [ -n "$BOX_MIB" ] && [ $((SOLD_MIB + RESERVE_MIB)) -gt "$BOX_MIB" ]; then
    echo "warning: sold out, ${LISTINGS_FILE} commits ${SOLD_MIB} MiB to tenants on a box" >&2
    echo "         with ${BOX_MIB} MiB, leaving less than the ~${RESERVE_MIB} MiB the provider's own" >&2
    echo "         containers and the host need. Lower a capacity or grow the box before the" >&2
    echo "         OOM killer chooses for you (README § \"Sizing the box\")." >&2
  fi
fi

if [ "$CONNECTOR_ONLY" = 1 ]; then
  echo "rendered connector.toml, the operator credential files and"
  echo "  nginx/conf.d/node.conf — NOT provider.toml (--connector-only)"
else
  echo "rendered provider.toml (0600 — a secret), connector.toml, the operator"
  echo "  credential files and nginx/conf.d/node.conf"
fi
echo "  ILP address         : ${ILP_ADDRESS}"
echo "  listings            : ${LISTINGS_FILE}"
echo "  paid ILP edge       : https://proxy.provider.${DOMAIN}/ilp"
echo "  health              : https://provider.${DOMAIN}/health"
echo "  certificate lineage : ${CERT_NAME}"
