//! Signing an operator write the way the connector verifies one: RFC 9421
//! HTTP Message Signatures over exactly `@method`, `@path` and an RFC 9530
//! `Content-Digest`, `alg="ed25519"`, `keyid` the signer's own public key in
//! hex, and a REQUIRED `expires` (connector `crates/connector-operator/src/
//! rfc9421.rs`, ADR 0008).
//!
//! This is a port of the connector's own `connector_operator::signing::
//! sign_request` — the function `connector send` signs `POST /packets` with —
//! and nothing more general: the same component order, the same
//! `@signature-params` serialisation, the same `sig1` label. ed25519 is
//! deterministic (RFC 8032), so for the same key and request the bytes are
//! identical to the connector's, which `tests` pins with vectors produced by
//! that function.

use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use ed25519_dalek::{Signer, SigningKey};
use sha2::{Digest, Sha256};

/// The covered components, in the order the connector requires: exactly
/// these, no more, no fewer.
pub const COVERED_COMPONENTS: [&str; 3] = ["@method", "@path", "content-digest"];

/// How long a signature stays valid: `connector send`'s own
/// `SIGNATURE_TTL_SECONDS`. The connector refuses it after `expires` and
/// remembers it until then, so it cannot be replayed.
pub const SIGNATURE_TTL_SECONDS: u64 = 60;

/// The three headers a signed write carries.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SignedWrite {
    pub signature_input: String,
    pub signature: String,
    pub content_digest: String,
}

/// The RFC 9530 `Content-Digest` of `body`: `sha-256=:<base64>:`.
pub fn content_digest(body: &[u8]) -> String {
    format!("sha-256=:{}:", BASE64.encode(Sha256::digest(body)))
}

/// The `keyid` a signature names: the public key in lowercase hex, which is
/// also the line an operator puts in the connector's `operator-write.keys`
/// (`OPERATOR_WRITE_KEY` in the deploy bundle's `.env`).
pub fn keyid_hex(key: &SigningKey) -> String {
    key.verifying_key()
        .to_bytes()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// RFC 9421 §2.3 `@signature-params`, serialised as the connector does.
fn signature_params(created: u64, expires: u64, keyid: &str) -> String {
    let inner = COVERED_COMPONENTS
        .iter()
        .map(|c| format!("\"{c}\""))
        .collect::<Vec<_>>()
        .join(" ");
    format!("({inner});created={created};expires={expires};keyid=\"{keyid}\";alg=\"ed25519\"")
}

/// The signature base: one line per covered component, then
/// `@signature-params`, joined by `\n` with no trailing newline.
fn signature_base(method: &str, path: &str, content_digest: &str, params: &str) -> String {
    [
        format!("\"@method\": {}", method.to_uppercase()),
        format!("\"@path\": {path}"),
        format!("\"content-digest\": {}", content_digest.trim()),
        format!("\"@signature-params\": {params}"),
    ]
    .join("\n")
}

/// Sign `method path` with `body`, valid from `created` to `expires`.
/// `path` is the request's path exactly as the connector will receive it —
/// no query, no origin.
pub fn sign_write(
    key: &SigningKey,
    method: &str,
    path: &str,
    body: &[u8],
    created: u64,
    expires: u64,
) -> SignedWrite {
    let content_digest = content_digest(body);
    let params = signature_params(created, expires, &keyid_hex(key));
    let base = signature_base(method, path, &content_digest, &params);
    let signature = key.sign(base.as_bytes());
    SignedWrite {
        signature_input: format!("sig1={params}"),
        signature: format!("sig1=:{}:", BASE64.encode(signature.to_bytes())),
        content_digest,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Produced by the connector's own `connector_operator::signing::
    /// sign_request` at tag `2026.09.11.1` (the image the deploy bundle
    /// pins), for the key whose seed is 32 bytes of `0x42`, `created`
    /// 1700000000 and `expires` 1700000060. The connector publishes no
    /// operator-write vectors in `vectors/wire-vectors.json`, so these were
    /// generated by calling that function from a scratch crate.
    const KEYID: &str = "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12";
    const VECTORS: [(&str, &[u8], &str, &str); 3] = [
        (
            "/channels/0xabababababababababababababababababababababababababababababababab/redeem-latest",
            b"",
            "sig1=:6sCXReqynediNEvHDATMA2VNBG0z/wt2gkYSsNYXGpKuNXOaGifp32GgFo/mRlRqZ2T/AFki4Gwho6pqgPX/Ag==:",
            "sha-256=:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=:",
        ),
        (
            "/channels/2aEVJ8koKD8LTZrLRSGtAtU7LBt4e7QjjCgf1kzQ7Rip/redeem-latest",
            b"",
            "sig1=:3E836PEVCdAE8V0O7fXxZ+x1AMJRqPmzTeIX74kNKrB9GD1XCYQbvWsk3LsRfEyskzSA5V6t79PwP78Qdl69DA==:",
            "sha-256=:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=:",
        ),
        (
            "/routes",
            b"{\"prefix\":\"g.example\"}",
            "sig1=:7dMb3SRRXICWx2SWkaShKP5H7kl3zps0MIBidbXJuwohk3eSVrYraKmFPqGauWToXw/0Y/r+oSxal7jcp7/PBg==:",
            "sha-256=:yKcJP2xUAhkg7+skTddThzi9udwCMKG3J1TuRVqviDo=:",
        ),
    ];

    #[test]
    fn signatures_match_the_connectors_own_signer_byte_for_byte() {
        let key = SigningKey::from_bytes(&[0x42; 32]);
        assert_eq!(keyid_hex(&key), KEYID);
        for (path, body, signature, digest) in VECTORS {
            let signed = sign_write(&key, "POST", path, body, 1_700_000_000, 1_700_000_060);
            assert_eq!(
                signed.signature_input,
                format!(
                    "sig1=(\"@method\" \"@path\" \"content-digest\");created=1700000000;\
                     expires=1700000060;keyid=\"{KEYID}\";alg=\"ed25519\""
                ),
                "{path}"
            );
            assert_eq!(signed.signature, signature, "{path}");
            assert_eq!(signed.content_digest, digest, "{path}");
        }
    }

    #[test]
    fn the_method_is_signed_upper_case() {
        let key = SigningKey::from_bytes(&[0x42; 32]);
        assert_eq!(
            sign_write(&key, "post", "/routes", b"x", 1, 2),
            sign_write(&key, "POST", "/routes", b"x", 1, 2)
        );
    }
}
